### ISSUE TITLE
Please add checking if function curl_reset exists before calling it

### ISSUE THREAD

**Issue by alexbarylo** [CircleOfNice/CiRestClientBundle#17]
Can you please add checking if function curl_reset exists before calling it, because curl_reset require PHP 5 >= 5.5.0 and I get fatal error on my php 5.4
File Services\Curl.php, line 97.
Thanks.

**Comment by TobiasHauck** [comment]
Will be fixed soon ;) Thank you for your notice.

**Comment by alexbarylo** [comment]
Sorry, your latest commit didn't help -- http://screencast.com/t/ONsuinEnoREZ
pleae check my pull request #19
