### ISSUE TITLE
Require lib-curl

### ISSUE THREAD

**Issue by davidrojo** [CircleOfNice/CiRestClientBundle#34]
Hello,

If curl is not installed the bundle will raise an error: 
ContextErrorException in CircleRestClientExtension.php line 54:
Warning: constant(): Couldn't find constant CURLOPT_HTTPHEADER

In the composer.json there should be a requirement for lib-curl. 

I am not very familiar with composer so I really don't know how to add it, but I think this can be added.

**Comment by TobiasHauck** [comment]
Hey David,

thank you for reporting this issue!

I deeply believe this is possible - even if don't know exactly how do do that right now. My first idea is just to add this line into the ```require``` section:

```
"ext-curl": "*"
```

May you be so kind and give it a try? Thanks a lot!
