### ISSUE TITLE
Exception when attempting to use

### ISSUE THREAD

**Issue by CRC-Mismatch** [CircleOfNice/CiRestClientBundle#46]
After following the basic configuration as explained in the README, whenever I try to use the bundle via either `$this->container->get('circle.restclient');` or `$this->get('circle.restclient');` I'm getting

> Error while setting a curl option (http://php.net/manual/de/function.curl-setopt.php). Tried to set  on curl resource.

Tried with 

> circle_rest_client:
>     curl:
>       defaults:
>         CURLOPT_HTTPHEADER:     [ 'Content-Type: application/x-www-form-urlencoded' ]
>         CURLOPT_FOLLOWLOCATION: true

and setting nothing in config.yml, to no avail.

**Comment by CRC-Mismatch** [comment]
Had curl installed but didn't have php-curl...

**Comment by TobiasHauck** [comment]
no problem, thank your for reporting anyways ;)
